# Generated by Django 2.0 on 2017-12-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('plate_numbers', models.CharField(max_length=20)),
                ('car', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('opened', models.BooleanField(default=True)),
                ('square_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('CF', 'Confirmed'), ('NC', 'Not confirmed'), ('IP', 'In progress'), ('IP', 'In progress')], default='NC', max_length=2)),
                ('come_date', models.DateTimeField()),
                ('leave_date', models.DateTimeField()),
                ('advance_payment', models.FloatField()),
                ('no_of_people', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalManagementDjango.Guest')),
                ('place_to_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalManagementDjango.PlaceToRent')),
            ],
        ),
    ]
