# Generated by Django 2.0 on 2018-02-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentalManagementDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CF', 'Confirmed'), ('NC', 'Not confirmed'), ('IP', 'In progress')], default='NC', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentalManagementDjango.ReservationStatus'),
        ),
    ]
