# Generated by Django 2.0 on 2018-02-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalManagementDjango', '0002_auto_20180211_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationstatus',
            name='status',
            field=models.CharField(default='Not confirmed', max_length=20),
        ),
    ]
