# Generated by Django 2.0 on 2018-02-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalManagementDjango', '0003_auto_20180212_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='come_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='leave_date',
        ),
    ]
